apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: ghcr.io/craftbyte/msi-nginx:v1
        # livenessProbe:
        #   exec:
        #     command:
        #     - service
        #     - nginx
        #     - status
        #   failureThreshold: 3
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        name: nginx
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
